version: "3"
services:
  nginx:
    image: sijunpark/docker_openresty_autossl:latest
    container_name: nginx
    restart: always
    volumes:
      - certificates:/certificates
      - nginx:/usr/local/openresty/nginx
      - ./nginx.conf:/usr/local/openresty/nginx/conf.d/default.conf
    links:
      - app:app.local
      - owncloud:cloud.local
      - wordpress:wordpress.local
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx"]
      interval: 30s
      timeout: 10s
      retries: 5
  base: &base
    image: node:12
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
  install:
    <<: *base
    entrypoint: npm i
  app:
    <<: *base
    container_name: app
    restart: always
    links:
      - redis:redis.local
    entrypoint: node_modules/.bin/nodemon app.js
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8080:8080
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    links:
      - db:db.local
    environment:
      WORDPRESS_DB_HOST: db.local
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://wordpress"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - wordpress:/var/www/html

  owncloud:
    image: owncloud/server:latest
    container_name: owncloud
    restart: always
    links:
      - db:db.local
      - redis:redis.local
    environment:
      - OWNCLOUD_DOMAIN=cloud.${ROOT_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=${MYSQL_USER}
      - OWNCLOUD_DB_PASSWORD=${MYSQL_PASSWORD}
      - OWNCLOUD_DB_HOST=db.local
      - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis.local
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_MULTIPLE_DATABASES=owncloud,wordpress
      - MYSQL_MAX_ALLOWED_PACKET=128M
      - MYSQL_INNODB_LOG_FILE_SIZE=64M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./initialize_mysql_multiple_databases.sh:/docker-entrypoint-initdb.d/initialize_mysql_multiple_databases.sh
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_DATABASES=1
    volumes:
      - redis:/var/lib/redis


volumes:
  certificates:
  nginx:
  node_modules:
  wordpress:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local
